// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {pcap} from '../models';

export function EnableCapture():Promise<void>;

export function FindInterfaces():Promise<Array<pcap.Interface>>;

export function GetPackets(arg1:string):Promise<void>;

export function PauseScan():Promise<void>;
