// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EnableCapture() {
  return window['go']['main']['App']['EnableCapture']();
}

export function FindInterfaces() {
  return window['go']['main']['App']['FindInterfaces']();
}

export function GetPackets(arg1) {
  return window['go']['main']['App']['GetPackets'](arg1);
}

export function PauseScan() {
  return window['go']['main']['App']['PauseScan']();
}
